name: Linux Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get -y install nasm libfdk-aac-dev libdrm-dev libva-dev
      
    - name: Configure library
      run: |
        mkdir upload
        git clone https://github.com/FFmpeg/FFmpeg.git
        cd FFmpeg
        git checkout release/8.0
        ./configure \
        --arch=x86_64 \
        --target-os=linux \
        --prefix=${{github.workspace}}/upload \
        --enable-gpl \
        --enable-nonfree \
        --enable-static \
        --disable-shared \
        --disable-all \
        --disable-everything \
        --disable-doc \
        --enable-avcodec \
        --enable-avformat \
        --enable-swresample \
        --enable-pthreads \
        --enable-error-resilience \
        --enable-decoder=h264,hevc,mpeg2video,vc1,vvc,vp8,vp9,av1,aac,ac3,dca,eac3,flac,mp3,opus,truehd,vorbis \
        --enable-demuxer=h264,hevc,mpeg2video,vc1,vvc,vp8,vp9,av1,aac,ac3,dca,eac3,flac,mp3,opus,truehd,vorbis \
        --enable-parser=h264,hevc,mpeg2video,vc1,vvc,vp8,vp9,av1,aac,ac3,dca,eac3,flac,mp3,opus,truehd,vorbis \
        --disable-decoder=libdav1d \
        --enable-libfdk-aac \
        --enable-vaapi \
        --disable-iconv \
        --disable-zlib \
        --disable-debug
        
    - name: Build library
      run: cd FFmpeg && make

    - name: Install library
      run: cd FFmpeg && sudo make install
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Linux-artifact
        path: ${{github.workspace}}/upload
        if-no-files-found: ignore
        retention-days: 0
