name: Windows Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  triplet: x64-windows-custom
        
jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
    - name: Download FFmpeg
      shell: pwsh
      run: |
        $AllProtocols = [System.Net.SecurityProtocolType]'Tls,Tls11,Tls12'
        [System.Net.ServicePointManager]::SecurityProtocol = $AllProtocols
        
        $ProgressPreference = 'SilentlyContinue'
        $ffmpeg_file = "C:\FFmpeg.zip"
        $ffmpeg_new_file = "C:\FFmpeg.8.0.zip"
        Invoke-WebRequest -Uri download https://github.com/faojdoai324234s/FFmpeg/archive/refs/heads/master.zip -OutFile $ffmpeg_file
        Invoke-WebRequest -Uri download https://github.com/faojdoai324234s/FFmpeg/archive/refs/heads/release/8.0-mpv.zip -OutFile $ffmpeg_new_file

    - name: Get FFmpeg hash
      shell: cmd
      run: |
        echo "FFmpeg hash:"
        vcpkg hash C:\FFmpeg.zip
        echo "FFmpeg 8.0 hash:"
        vcpkg hash C:\FFmpeg.8.0.zip
        
    - name: Install FFmpeg
      shell: cmd
      run: |
        agit clone https://github.com/microsoft/vcpkg
        cd vcpkg
        copy /y /v ${{github.workspace}}\${{ env.triplet }}.cmake triplets
        copy /y /v ${{github.workspace}}\portfile.cmake ports\ffmpeg
        vcpkg install ffmpeg[avcodec,avformat,fdk-aac,nonfree,swresample]:${{ env.triplet }}
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Windows-artifact
        path: ${{github.workspace}}/vcpkg/installed/${{ env.triplet }}
        if-no-files-found: ignore
        retention-days: 0
